### PR TITLE
Use travis ci containers

### PR DESCRIPTION
**Pull request by itziakos**
This PR add travis-ci run on codetools using the container setup. Tests run on python 2.6, 2.7 and 3.4 (with allowed failures).

### CODE REVIEW

**Comment by itziakos** [comment]
This PR is ready for review

**Comment by corranwebster** [comment]
LGTM - feel free to merge

**Comment by corranwebster** [comment]
Although I would have absolutely no expectation of passing Python 3 tests anytime soon.  The `Block` class would need to be completely re-written.

**Comment by itziakos** [comment]
thanks corrant

**Pull request merged**
