### PR TITLE
Add manifest file

### LINKED ISSUE #35: Test failures on Python 3
Three test failures are seen when installing codetools from pypi in a python 3 env. Note that some of the dependencies need to be installed manually as they are not specified in the codetools setup script. See #26 .

```
======================================================================
ERROR: Assigning floats to arrays
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rporuri/.edm/envs/temp3/lib/python3.6/site-packages/codetools/contexts/tests/with_mask_test_case.py", line 44, in test1
    file_object = open(os.path.join(self.code_dir,'test1.py'), 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/rporuri/.edm/envs/temp3/lib/python3.6/site-packages/codetools/contexts/tests/with_mask_codes/test1.py'

======================================================================
ERROR: Different sized arrays
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rporuri/.edm/envs/temp3/lib/python3.6/site-packages/codetools/contexts/tests/with_mask_test_case.py", line 65, in test2
    file_object = open(os.path.join(self.code_dir,'test2.py'), 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/rporuri/.edm/envs/temp3/lib/python3.6/site-packages/codetools/contexts/tests/with_mask_codes/test2.py'

======================================================================
ERROR: Same sized array assignments within 'with' block
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rporuri/.edm/envs/temp3/lib/python3.6/site-packages/codetools/contexts/tests/with_mask_test_case.py", line 86, in test3
    file_object = open(os.path.join(self.code_dir,'test3.py'), 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/rporuri/.edm/envs/temp3/lib/python3.6/site-packages/codetools/contexts/tests/with_mask_codes/test3.py'
```

The errors are because `.../with_mask_codes/` doesn't contain an `__init__` file so the `test*.py` files in the submodule aren't included in the sdist uploaded to pypi.

### PR DESCRIPTION
**Pull request by rahulporuri**
fixes #35 and #34

### CODE REVIEW

**Comment by mdickinson** [comment]
LGTM. I'm not convinced that this fully fixes #35, though: it'll fix it for the sdist, but for egg builds, we'll want to include these files in the `package_data`, too.

**Comment by rahulporuri** [comment]
> LGTM. I'm not convinced that this fully fixes #35, though: it'll fix it for the sdist, but for egg builds, we'll want to include these files in the `package_data`, too.

I just tested and checked that #35 is fixed i.e. the files are available in the egg. I'll update `package_data` for redundancy.

**Comment by rahulporuri** [comment]
Merging.

**Comment by mdickinson** [comment]
> I just tested and checked that #35 is fixed i.e. the files are available in the egg.

How did you test? If I use `python setup.py bdist_egg`, _without_ the `package_data` changes, then I get an egg in which the images aren't present. The MANIFEST.in file doesn't get used when building an egg as opposed to a source distribution.

IOW, the package_data update is necessary. It's not just "for redundancy".

**Comment by rahulporuri** [comment]
> How did you test? If I use `python setup.py bdist_egg`, _without_ the `package_data` changes, then I get an egg in which the images aren't present.

Oops. I only tested for the py files in `.../with_mask_codes/`, not for the image files. Thanks for testing.

**Comment by mdickinson** [comment]
Hmm. I guess I reviewed this too hastily. Why is it necessary to include the `.py` files at all? I'd expect those to get picked up in the usual way by the `find_packages` call.

**Comment by mdickinson** [comment]
> Hmm. I guess I reviewed this too hastily. Why is it necessary to include the `.py` files at all? I'd expect those to get picked up in the usual way by the `find_packages` call.

Ah, right sorry. Remembering now. Those `.py` files are test data, not test scripts... Sorry for the noise.

**Pull request merged**
